wsgi/blog/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns

wsgi/web/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from rest_framework.authtoken.views import obtain_auth_token
from blogapi.urls import router

import settings
admin.autodiscover()


urlpatterns = patterns('',
    # url(r'^$', 'web.views.home', name='home'),
    #    url(r'^index/', include('web.blog.urls')),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/token/', obtain_auth_token, name='api-token'),
    url(r'^api/', include(router.urls)),
)

urlpatterns +=  i18n_patterns('blog.views',
#   url(r'^index/', include('blog.urls')),

   
    url(r'^$', 'index',name='home'),
    url(r'^index', 'index',name='home'),
    url(r'^/index/(?P<orderby>\w+)/',"index",name='home'),
    url(r'^blog/page/pid=(\d+)', "viewpage",name='view'),
    url(r'^blog/page', "list", name='page'),
    url(r'^blog/contact', "contact",name='contact'),
    url(r'^blog/menu', "menu"),
    url(r'^blog/admin', "manager",name='manager'),
    url(r'^blog/video', "video",name='video'),
    url(r'^search/', include('haystack.urls')),
    url(r'^gallery/list', "gallery",name='gallery'),
)

urlpatterns +=  i18n_patterns('userprofile.views',

    url(r'^blog/login', "logins",name='login'),
    url(r'^blog/register', "signup",name='register'),
    url(r'^blog/logout', "out",name='logout'),
    url(r'^blog/user', "usercp",name='profile'),
    
    
)

urlpatterns += i18n_patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

wsgi/blog/models.py
from django.db import models
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
import os
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from  web import settings
# Create your models here.
class Category(models.Model):
    
    title_category = models.CharField(max_length=150)
    post = models.TextField()
    tags = models.TextField()
    url = models.URLField(blank=True)
    hide= models.BooleanField(default=True)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.title_category
    
    def save(self, *args, **kwargs):
        self.url ="http://url.com/"
        super(Category, self).save(*args, **kwargs) 
        
    def get_absolute_url(self):
        
        return "/index?category={0}".format(self.title_category)
    
    class Meta:
        verbose_name = 'Categories'
        verbose_name_plural = 'Categories'
        ordering = ['-pub_date']
 
    
class Tag(models.Model):
    name = models.CharField(max_length=150)
    category_id = models.ForeignKey(Category)
    frequency = models.IntegerField()    
    def __unicode__(self):              # __unicode__ on Python 2
        return self.name
    
    def insert(self):
        pass
    
    def updateFrequency(self):
        pass
    
    def deleteTag(self):
        pass
    
class Page(models.Model):
    title=models.CharField(max_length=150,help_text="Title of you post")
    topic = models.TextField()
    category_id = models.ForeignKey(Category,related_name='pages')
    img_url =models.URLField(blank=True)
    hide =models.BooleanField(default=True)
    url = models.URLField(blank=True)
    pub_date = models.DateTimeField('date published')
    
class Gallery(models.Model):
    title = models.CharField(max_length=150,help_text="title")
    avatar = models.ImageField(upload_to='avatars')
    avatar_thumbnail = ImageSpecField(source='avatar',
                                      processors=[ResizeToFill(300, 200)],
                                      format='JPEG',
                                      options={'quality': 60})
    pos  = models.IntegerField()
    hide = models.BooleanField(default=True)
    class Meta:
        verbose_name = 'Gallery'
        verbose_name_plural = 'Gallery'
        
 
    
    
@receiver(pre_delete, sender = Gallery)
def delete_pic(instance, **kwargs):
    
    print(instance.avatar)
    url="{0}/{1}".format(settings.MEDIA_ROOT,instance.avatar) 
    os.remove(url)
    
    




class Comment(models.Model):
    title=models.CharField(max_length=150)
    page_id = models.ForeignKey(Page,related_name='comments')
    topic = models.TextField()
    category_id = models.ForeignKey(Category)
    hide =models.BooleanField(default=True)
    pub_date = models.DateTimeField('date published')
    
class Config(models.Model):  
    title =models.CharField(max_length=150)
    page_num =models.CharField(max_length=150)
    statu = models.BooleanField(default=True)
    meta_info = models.TextField()
    site_url =  models.URLField(blank=True)
    cache_time = models.IntegerField()
    
class Item(models.Model):
    title =models.CharField(max_length=150)
    item_url =  models.CharField(max_length=150)
    item_id =models.ForeignKey('self')
    hide = models.BooleanField(default=True)
    pos = models.IntegerField()
    
    def __unicode__(self):
        return self.title

wsgi/blog/views.py
from django.shortcuts import render_to_response , redirect, get_object_or_404
from django.core.context_processors import request
from blog.models import Category, Page, Item , Gallery
from blog.form import  Contact, FileUpload
from django.core.context_processors import csrf
from django.views.decorators.csrf import csrf_exempt
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.utils.translation import  activate, ugettext as _
from django.template import RequestContext
from django.core import serializers
from django.http import HttpResponse


# sort post by time

    
#     @method_decorator(login_required)


    
    
def index(request, orderby='-pub_date'):
    
        site = _('site')
    #     activate('ru')
        
        categories = Category.objects.all()
        if(request.GET.get('q')):
            s = request.GET.get('q')
            categories = categories.filter(title_category__istartswith=s)
        if(request.GET.get('tag')):
            tag = request.GET.get('tag')
            categories = categories.filter(title_category__icontains=tag) 
        if(request.GET.get('category')):
            category = request.GET.get('category')       
            categories = categories.filter(title_category__icontains=category)
        if  request.GET.get('filter'):
            cat = request.GET.get('filter')
            categories = categories.filter(title_category__icontains=cat)
        if  request.GET.get('orderby') == 'name':
            categories = categories.order_by('title_category')
            
        elif  request.GET.get('orderby') == 'date':
            categories = categories.order_by('pub_date')
        else:
            categories = categories.order_by(orderby)
            
       
            
        paginator = Paginator(categories , 2)
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)
        return render_to_response("blog/index.html",
                                  {"lists":contacts, 'site':site}, RequestContext(request))
       
def handle_uploaded_file(f):
        with open('web/media/upload/name.jpg', 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)    
                
def home(request):
        if request.is_ajax():
            pass   
        
@login_required(login_url='/blog/login/')
def list(request):
        
        msg = messages.get_messages(request)
        form = FileUpload()
        if request.method == 'POST':
            form = FileUpload(request.POST, request.FILES)
            if form.is_valid():
                handle_uploaded_file(request.FILES['file'])
                messages.success(request, 'Welcome to security page.')
                return redirect('/index/')
            else:
                return redirect('/blog/list')
        else:
            return render_to_response("blog/page.html", {"post":"Secound", 'messages':msg, 'file':form}
                                        , RequestContext(request))
    
def viewpage(request, pid):
        try:
            post = Page.objects.get(id=pid)
        except Page.DoesNotExist:
            raise Http404("Not found")
            
        return render_to_response("blog/view.html", {'data':post}, RequestContext(request))
    
@csrf_exempt
def video(request):
        pass
        video = {}
        return render_to_response("blog/video.html", {'data':video}, RequestContext(request))
           
def gallery(request):
        
        foto = Gallery.objects.all()
        paginator = Paginator(foto , 2)
        page = request.GET.get('page')
        try:
            pthotos = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            pthotos = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            pthotos = paginator.page(paginator.num_pages)
        return render_to_response("blog/gallery.html", {'fotos':pthotos}, RequestContext(request))
                
        
    
@permission_required('blog.can_publish', login_url='/index/')
    
    
def manager(request): 
        return render_to_response("blog/manager.html", {"data":"Hello manager"}, RequestContext(request))  
    
def menu(request): 
        data = serializers.serialize("json", Item.objects.all()) 
        return HttpResponse(data)       
    
@csrf_exempt
def contact(request, **r):
        form = Contact()
        if request.POST:
            data = request.POST
            form = Contact(data)
            if form.is_valid:
                pass
                # data= send_mail('Thanks you', 'Contact from', 'from@example.com',['to@example.com'], fail_silently=False)
                return render_to_response("blog/contact.html", {"form":form, "data":data}, RequestContext(request))
            else:
                raise Http404("Not found")
        else:
            return render_to_response("blog/contact.html", {"form":form}, RequestContext(request))
        
    

wsgi/web/templates/blog/contact.html
{% extends "layout.html" %}
{%block content %}
<div class="col-md-7">
	<h3>Contact Just</h3>
	
	<form  class="form-horizontal" role="form" action="/{{LANGUAGE_CODE}}/blog/contact" method="post">
	 <div class="form-group">	
	{{form.as_p}}
	{% csrf_token %}
	 <input type="submit" class="form-control btn-primary" value="Submit" />
	 </div>
</form>
</div>
{%endblock %}

wsgi/web/templates/blog/cp.html
{% extends "layout.html" %}
{%block content %}
<div class="col-md-5">
	
	{%if data %}
	{{data}}
	{% endif %}
	<h3>Login</h3>
	<form class="form" action="{% url "login" %}" method="post">
		
	{{form.as_p}}
	{% csrf_token %}
	 <input type="submit"  class="form-control btn-primary"value="Submit" />
</form>
<a href="{% url "register" %}" >SignUp now</a>
</div>
{%endblock %}

wsgi/web/templates/blog/gallery.html
{% extends "layout.html" %}
{%block content %}
<div class="page-header">
  <h1>Fotos &nbsp;<small>for Fun</small></h1>
</div>
<div class="row">
	<div class="col-md-6">
	{%if fotos%}
	
	<ul class="media-list">
{%for foto in fotos %}
  <li class="media">
    <a class="pull-left bfoto" rel="group" href="/media/{{ foto.avatar }}">
      <img class="media-object img-rounded " src="{{ foto.avatar_thumbnail.url }}" alt="{{foto.title}}">
    </a>
    <div class="media-body">
      <h4 class="media-heading">{{foto.title}}</h4>
      
    </div>
    <hr/>
  </li>
  {% endfor %}
</ul>
</div>

</div>
{% include  "navigation.html" with pages=fotos %}
{%endif %}
{%endblock %}

wsgi/web/templates/blog/index.html
{% extends "layout.html" %}
{% block content %}
<div> 
	{% load i18n %}
	


	<div class="row">

<div class="dropdown downsp" style="float: left">
	<span class="filter">Sort by: </span>
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    
    <span class="glyphicon glyphicon-collapse-down "></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="?orderby=date">Date</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="?orderby=name">Name</a></li>
     </ul>
</div>

<div class="dropdown" style="float: left;padding-left: 10px">
	<span class="filter">Filter: </span>
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    
    <span class="glyphicon  glyphicon-chevron-down "></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
  	{% for filter in lists%}
    <li role="presentation"><a role="menuitem" tabindex="-1" href="?filter={{filter.title_category}}">{{filter.title_category}}</a></li>
    {%endfor%}

  </ul>
</div>
</div>
<div>
			<br/>
			{% include "tabs.html" with datas=lists %}
			<hr/>
			
			{%if not lists%}
        <p>No Category </p>
        {%endif %}
			{% for article in lists%}
			
			<h3>{{article.title_category}}</h3>
			{%for data in article.page_set.all %}
			<h4>{{data.title}}</h4>
			<p>{{data.topic | safe}}</p>
			<div class="downsp">
			
			</div>
<a class="btn btn-sm btn-default " href="{% url "view"   data.id %}">
					More</a>
			<hr>
	
	{%endfor %}
	
				<p><hr>
					Tags: {%for tag in article.tag_set.all %}
					
					<span class="badge">
{{tag.name}} 
					</span>
					{%endfor%}
					</p>
				
				
			{%endfor%}
		</div>
		<br/>
			
		{% include  "navigation.html" with pages=lists %}
        </div>
        
        
{% endblock %}
	

wsgi/web/templates/blog/manager.html
{% extends "layout.html" %}
{% block content %}
<div class="contact">
	
	{#{{perms.web}}#}
	
	{% if perms.blog.can_publish %}
	<p>Toka для избранных</p>
	{% else%}
	Not valid
	{% endif %}
	
</div>
{%endblock %}

wsgi/web/templates/blog/page.html
{% extends "layout.html" %}
{%block content %}
<div  class="col-md-5">
	
	<h3>Upload File</h3>
	<form class="form" action="/{{LANGUAGE_CODE}}/blog/list" method="post" enctype="multipart/form-data">
		
	{{file.as_p}}
	{% csrf_token %}
	 <input type="submit"  class="form-control btn-primary"value="Submit" />
</form>
</div>
{%endblock %}

wsgi/web/templates/blog/register.html
{% extends "layout.html" %}
{%block content %}
<div class="col-md-5">
<form class="form" action="/{{LANGUAGE_CODE}}/blog/register" method="post">
		{{data}}
	{{form.as_p}}
	{% csrf_token %}
	 <input type="submit"  class="form-control btn-primary" value="Submit" />
</div>
{%endblock %}

wsgi/web/templates/blog/user.html
{% extends "layout.html" %}
{%block content %}
<div class="user">
	<h3>	{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
{% else %}
    <p>Welcome, new user. Please log in. <a href="/blog/logout">Login</a></p>
    
{% endif %}</h3>
	<a href="{% url "logout" %}">Logout</a>
	
</div>
{%endblock %}

wsgi/web/templates/blog/video.html
{% extends "layout.html" %}
{%block content %}

<iframe width="560" height="315" src="//www.youtube.com/embed/vtKNY35oUg4" frameborder="0" allowfullscreen></iframe>
<hr>
<form class="form" action="/{{LANGUAGE_CODE}}/blog/video" method="post">
	<input type="text"  placeholder="Video search" name="seach" class="s"/>
	{% csrf_token %}
	<input type="submit"  value="search"/>
</form>
{%endblock %}

wsgi/web/templates/blog/view.html
{% extends "layout.html" %}
{%block content %}
<div>
	<h4>
		{{data.title}}
	</h4>
	<p>{{data.topic|safe}}</p>
	<em class="downsp cl">{{data.pub_date|date}}</em>
<br/>
	<a class="btn btn-primary" href="/{{LANGUAGE_CODE}}/index">Back</a>
	<hr/>
	<h4>Comments ({{data.comment_set.all.count}})</h4>

{% for comment in data.comment_set.all %}
<p>{{comment.title}}</p>
<p>{{comment.topic}}</p>
<p>{{comment.pub_date}}</p>
<hr />
{% endfor%}
</div>
{%endblock%}